version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
