services:
  lazymc:
    container_name: lazymc
    environment:
      # point to the service name of the minecraft server
      - SERVER_ADDRESS=mc:25565
      # required to find the container to manage it
      - LAZYMC_GROUP=mc
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/server:ro
    ports:
      # lazymc-docker-proxy acts as a proxy so there is
      # no need to expose the server port on the minecraft container
      - "25565:25565"
    build: .

  # standard docker minecraft server, also works with other server types
  mc:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    # We need to add a label here so that lazymc-docker-proxy knows which
    # container to manage
    labels:
      - lazymc.group=mc
    tty: true
    stdin_open: true
    # This container should be managed solely by the lazymc container
    # so set restart to no, or else the container will start again...
    restart: no
    environment:
      EULA: "TRUE"
    volumes:
      - data:/data

volumes:
  data:
