services:

  lazymc:
    ports:
      - '25565:25565'
    container_name: lazymc
    environment:
      - SERVER_ADDRESS=mc:25565
      - DEBUG=true
      - LAZYMC_GROUP=mc
      - RUST_LOG=trace
      - TIME_MINIMUM_ONLINE_TIME=10
      - TIME_SLEEP_AFTER=10
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/server:ro
    build: .

  mc:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    labels: 
      - lazymc.group=mc
    tty: true
    stdin_open: true
    restart: no
    environment:
      EULA: "TRUE"
    volumes:
      - data:/data

volumes:
  data: