name: Build And Push Docker Image
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build And Push
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: docker
        uses: ./.github/actions/docker
        with:
          publish: true
    
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Update changelog
        id: update_changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v3
        with:
          tag: ${{ steps.tag.outputs.tag }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Release ${{ github.ref_name }}
          branch: release/${{ github.ref_name }}
          labels: release
          commit-message: "[ci skip] update changelog for ${{ github.ref_name }}"
          body: This PR was created by the release workflow.
